name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Zip files
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'bla.zip'
        exclusions: '*.git* *.github* LICENSE *.md sounds/*.md'

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "bla.zip"
